### PR TITLE
Added token expiry check + renew

### PR DESCRIPTION
**Pull request by ipetepete**
Addresses token renewal, auto renews token when expired.

### CODE REVIEW

**Review by jacquesalice — CHANGES_REQUESTED** [review]
@ipetepete thanks! Two things. First, when I tried to run the client tests, I get an import error:
```
ModuleNotFoundError: No module named 'jwt'
```

Will the jwt package have to be installed on each machine in order for the client to run? If so, you should ask Sean to add it to puppet. Is it just a pip install?

Second, running flake8 gives me an error that wasn't there before (ignoring the errors from the `./source/conf.py` file for now):
```
./sparcl/client.py:126:39: E261 at least two spaces before inline comment
```
Can you fix that quick?

**Comment by ipetepete** [comment]
I added the package PyJWT to the requirements-client.py file. I forgot to add it after I installed in on my dev. Also fixed the spaces in the comment. Thanks!

**Comment by jacquesalice** [comment]
@ipetepete Hmm the Auth Tests don't seem to work on this branch when ran against sparc1. Did the tests pass on your DEV? As devops on sparc1 in /home/ajacques/sparclclient on the `token_expiry_DLS-507` branch (actual usrpw redacted from this copy/paste for security):
```
(venv) [devops@sparc1 sparclclient]$ usrpw='<redacted>' serverurl=https://sparc1.datalab.noirlab.edu/ python -m unittest tests.tests_api.AuthTest

    Running Client Tests
      against Server:   "sparc1.datalab.noirlab.edu"
      comparing to:     tests.expected_pat
      showact=False
      showcurl=False
      client=(sparclclient:1.2.2, api:12.0, https://sparc1.datalab.noirlab.edu/sparc, client_hash=9f79c19c169fe882f8aedccf4ae71db1b535b79a, verbose=False, connect_timeout=1.1, read_timeout=5400.0)

    For REPRODUCIBLE RESULTS rebuild Server DB before running tests!
    Use: init-db.sh
    
E
======================================================================
ERROR: setUpClass (tests.tests_api.AuthTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ajacques/sparclclient/tests/tests_api.py", line 773, in setUpClass
    cls.client.find(
  File "/home/ajacques/sparclclient/sparcl/client.py", line 624, in find
    raise ex.genSparclException(res, verbose=self.verbose)
sparcl.exceptions.AccessNotAllowed: [DSDENIED] uname='ANONYMOUS' is declined access to datasets=['SDSS-DR17-test']; drs_requested=['SDSS-DR17-test'] my_auth=['BOSS-DR16', 'DESI-EDR', 'SDSS-DR16']

----------------------------------------------------------------------
Ran 0 tests in 1.019s

FAILED (errors=1)
```
But they DO work when on the `main` branch:

```
(venv) [devops@sparc1 sparclclient]$ usrpw='<redacted>' serverurl=https://sparc1.datalab.noirlab.edu/ python -m unittest tests.tests_api.AuthTest

    Running Client Tests
      against Server:   "sparc1.datalab.noirlab.edu"
      comparing to:     tests.expected_pat
      showact=False
      showcurl=False
      client=(sparclclient:1.2.2, api:12.0, https://sparc1.datalab.noirlab.edu/sparc, client_hash=1ed890aaccb766dc2273f05215a013bb967befbe, verbose=False, connect_timeout=1.1, read_timeout=5400.0)

    For REPRODUCIBLE RESULTS rebuild Server DB before running tests!
    Use: init-db.sh

...................
----------------------------------------------------------------------
Ran 19 tests in 15.002s

OK
```
Is there something new you did to client.py that would cause this behavior?

**Comment by ipetepete** [comment]
Yeah the tests pass on my local running the client against my local sparcserver. Let me take a look. Is sparc1 running the same dev branch also?

**Comment by jacquesalice** [comment]
sparc1 uses the `pat` branch from the sparcserver repo (which was just updated with your changes). Then in the sparclclient repo I made the `main` branch and the `token_expiry_DLS-507` branch run against the `https://sparc1.datalab.noirlab.edu` server

**Review by jacquesalice — APPROVED** [review]
client tests pass against sparc1 server. Merging!

**Pull request merged**
